var listPortfolioOption =

[
    ["Technical","ENHANCED ECOMMERCE IMPLEMENTATIONS - BHINNEKA","TS1"],
    ["Technical","ADVANCED ENHANCED ECOMMERCE TECHNICAL IMPLEMENTATION","TS2"],
    ["Technical","GOOGLE ANALYTICS TRACKING IMPLEMENTATION - TEMPO","TS3"],
    ["Technical","CROSS-DEVICE & ENHANCED ECOMMERCE TRACKING - JD THAILAND","TS4"],
    ["Advisory","BANNER DESIGN TEST (SINGLE VS MULTIPLE PRODUCT)","AS1"],
    ["Advisory","OWNED CHANNEL OPTIMIZATION- MISTER ALADIN","AS2"],
    ["Advisory","MOBILE APP USER-JOURNEY & ENGAGEMENT OPTIMIZATION - SALSFC","AS3"]

]